create schema if not exists set_query;

set search_path to set_query;

drop table if exists notunq_pi;
CREATE table notunq_pi
(
   id INT PRIMARY KEY
);
comment on table notunq_pi is 'id value of people_income table duplicate rows, original + duplicates';



drop table if exists unq_people_income;
CREATE table unq_people_income
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table unq_people_income is 'copy of people_income table with duplicated rows removed';


drop table if exists dups_people_income;
CREATE table dups_people_income
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table dups_people_income is 'duplicate rows from people_income table with filtered-duplicates rows removed';


drop table if exists set_pi_data1;
CREATE table set_pi_data1
(
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_pi_data1 is 'table of approx 10 percent random sample of non-duplicated unq_people_income data';

drop table if exists set_pi_data2;
CREATE table set_pi_data2
(
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_pi_data2 is 'table of approx 10 percent random sample of non-duplicated unq_people_income data';

drop table if exists set_pi_data3;
CREATE table set_pi_data3
(
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_pi_data3 is 'table of approx 10 percent random sample of non-duplicated unq_people_income data';


drop table if exists set_cat;
CREATE table set_cat
(
   id INT,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_cat is 'union all operations (duplicates retained) applied to three approx 10 percent random sampled data';


drop table if exists set_unioned;
CREATE table set_unioned
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_unioned is 'union operations (duplicates removed) applied to three approx 10 percent random sampled data';


drop table if exists set_intersect;
CREATE table set_intersect
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table set_intersect is 'intersection operation  (with No duplicates)';

drop table if exists unq_pi_minus_data1;
CREATE table unq_pi_minus_data1
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);
comment on table unq_pi_minus_data1 is 'set minus opertation--unq_people_income table MINUS set_pi_data1 table';


