create schema if not exists data_query;

set search_path to data_query;

drop table if exists people_income;

CREATE table people_income
(
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   age integer,
   workclass varchar,
   fnlwgt integer,
   education varchar,
   education_num integer,
   marital_status varchar,
   occupation varchar,
   relationship varchar,
   sex varchar,
   capital_gain integer,
   capital_loss integer,
   hours_per_week integer,
   native_country varchar,
   income varchar
);

comment on table people_income is 'table used to  mirror python Dataframe analysis as postgres queries';
